<?php


// IN DEPLOY CHANGE TO FALSE
putenv('DISPLAY_ERRORS_DETAILS=' . true);

//DB - O DEPLOY PUT YOUR CONFIG - THIS CONFIG IS TO XAMPP
putenv('DB_QS_CONDOMINIO_HOST=localhost');
putenv('DB_QS_CONDOMINIO_PORT=3306');
putenv('DB_QS_CONDOMINIO_DBNAME=db_qscondominio');
putenv('DB_QS_CONDOMINIO_USER=root');
putenv('DB_QS_CONDOMINIO_PASSWORD=');
